name = "worker-template-postgres"
compatibility_date = "2021-10-07"
main = "./dist/index.mjs"

[build]
command = "npm install && npm run build-and-copy-wasm"

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true
